include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: false # we log BLE/LED traffic during bring-up
    use_key_in_widget_constructors: true

analyzer:
  errors:
    # treat unawaited futures as warnings, not errors, during bring-up
    unawaited_futures: warning
