M48
; DRILL file {KiCad 9.0.4} date 2026-06-02T16:18:24-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-02T16:18:24-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X119.61Y-104.5
X125.39Y-104.5
T2
X102.5Y-109.0
X103.0Y-63.5
X154.0Y-58.0
X154.5Y-109.0
M30
