// AUTO-GENERATED by scripts/gen-voice-lines.mjs — DO NOT EDIT.
// Maps voiceKey(text) -> bundled audio module for pre-generated instructor
// lines. Empty until `npm run voice` is run with a Google TTS API key
// (see docs/SERVICES_SETUP.md); speak() falls back to live TTS for any line
// missing here, so an empty map is always safe.

/** TTS voice the bundled clips were synthesized with ('' = none yet). */
export const VOICE_NAME = '';

export const VoiceLineMap: Record<string, number> = {};
